services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
    volumes:
      - ./vistoria_back:/app/vistoria_back 
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
